on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 47 */6 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - run: git clone https://noeljacob:${{ github.token }}@github.com/noeljacob/aur.git ./;
#    - run: |
#        mkdir $HOME/.ssh &&
#        echo $SSH_KEY > $HOME/.ssh/aur_ed2551 &&
#        chmod 600 $HOME/.ssh/aur_ed2551
#      env:
#        SSH_KEY: ${{ secrets.SSH_KEY }}
    - run: node dist/index.js
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}