on:
  workflow_dispatch:
  schedule:
    - cron: 47 */6 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - run: which node
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}