on:
  workflow_dispatch:
  schedule:
    - cron: 47 */6 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - run: |
        git config --global credential.helper cache;
        git clone git clone https://noeljacob:${{ github.token }}@github.com/noeljacob/aur.git;
    - run: node -v
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}