name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '*/11 * * * *'
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -L \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://github.com/NoelJacob/aur/releases/latest/download/aur \
          -o ./aur
    - run: chmod +x ./aur
    - run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
    - run: ./aur
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SSH_PUB: ${{ secrets.SSH_PUB }}
