on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 47 */6 * * *

jobs:
  update:
    runs-on: archlinux:base-devel
    steps:
    - run: git clone https://noeljacob:${{ github.token }}@github.com/noeljacob/aur.git ./;
    - run: node dist/index.js
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}