name: Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.7.3
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: nightly
        components: rust-src
    - name: Build
      run: cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-gnu --release
    - name: Extract version
      run: |
        version=$(grep "^version" Cargo.toml | head -1 | awk -F\" '{print $2}')
        echo "VERSION=$version" >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "target/x86_64-unknown-linux-gnu/release/aur"
        commit: "master"
        generateReleaseNotes: true
        makeLatest: "latest"
        # tag: ${{ env.VERSION }}
